/*******************************************/
/*																				**/
/* 						Debug Menu Strings					**/
/*																				**/
/*******************************************/

#ifndef __DEBUG_MENU_STRINGS_H
#define __DEBUG_MENU_STRINGS_H

#include <stdint.h>
#include "debug_utils.h"

#define MAX_DEBUG_MENU_STRLEN	75
#define USER_PROMPT "$>"
#define USER_PROMPT_LEN strlen(USER_PROMPT)


enum _E_DBG_CMDS
{
	HELP_DBG_CMD,
	TILE_DBG_CMD,
	MOTION_DBG_CMD,
	
	NUM_E_CMDS
};	

enum _E_MESSAGES
{
	PRESS_A_KEY_MSG,
	WELCOME_MSG,
	HELP_PROMPT_MSG,
	ERR_CMD_NOT_FOUND_MSG,
	ERR_OCCURRED_MSG,
	ERR_UNKNOWN_MSG,
	ERR_NO_RESP_MSG,
	ERR_RESOURCE_LOCK_MSG,
	TILE_NOT_INIT_MSG,
	GET_CONFIG_MSG,
	DATETIME_USAGE_MSG,
	GET_DATETIME_MSG,
	GET_FIRMWAREVERSION_MSG,
	GPSJAM_USAGE_MSG,
	GET_GPSJAM_MSG,
	SPOOF_UNKNOWN_MSG,
	SPOOF_NONE_MSG,
	SPOOF_IND_MSG,
	SPOOF_MULT_MSG,
	GEO_USAGE_MSG,
	GET_GEO_MSG,
	GPIO_USAGE_MSG,
	GET_GPIO_MSG,
	GPIO_MODE_0_MSG,
	GPIO_MODE_1_MSG,
	GPIO_MODE_2_MSG,
	GPIO_MODE_3_MSG,
	GPIO_MODE_4_MSG,
	GPIO_MODE_5_MSG,
	GPIO_MODE_6_MSG,
	GPIO_MODE_7_MSG,
	GPIO_MODE_8_MSG,
	GPIO_MODE_9_MSG,
	GPIO_MODE_10_MSG,
	GPSFIX_USAGE_MSG,
	GET_GPSFIX_MSG,
	GPSFIX_NR_MSG,
	GPSFIX_DR_MSG,
	GPSFIX_G2_MSG,
	GPSFIX_G3_MSG,
	GPSFIX_D2_MSG,
	GPSFIX_D3_MSG,
	GPSFIX_RK_MSG,
	GPSFIX_TT_MSG,	
	GPSFIX_UNKNOWN_MSG,
	GET_POWEROFF_MSG,
	PWRSTS_USAGE_MSG,
	GET_POWERSTATUS_MSG,
	GET_RESTART_MSG,
	GET_RXDATA_MSG,
	RXTEST_USAGE_MSG,
	GET_RXTEST_MSG,
	GET_STATUS_MSG,
	SLEEP_USAGE_MSG,
	GET_SLEEP_MSG,
	TXDATA_USAGE_MSG,
	GET_TXDATA_MSG,
	TXMSGS_USAGE_MSG,
	GET_TXMSGS_MSG,
	RXMSGS_USAGE_MSG,
	GET_RXMSGS_MSG,
	GYRO_ACCEL_USAGE_MSG,
	MOTION_EVENT_USAGE_MSG,
	
	NUM_E_MESSAGES
};

typedef struct _S_CMD_LIST {
	uint8_t cmd_index;
	uint8_t cmd_name[25];
	void (*cmd_func)(ARG_LIST args);
} S_CMD_LIST;

#endif	/* __DEBUG_MENU_STRINGS_H */