#include "debug_menu_strings_en.h"

uint8_t MESSAGES[NUM_E_MESSAGES][MAX_DEBUG_MENU_STRLEN] = 
{
		"Press a key to begin.\n",
		"\n********* Welcome to Qube! *********\n",
		"Type `help` or `?` for a list of commands\n\n",
		"Command not found.\n",
		"ERROR: An error has occurred.\n",
		"ERROR: An unknown error has occurred.\n",
		"ERROR: No response from device.\n",
		"ERROR: Resource locked.",
		"ERROR: Tile is not initialized.\n",
		"Getting config...\n\n",
		"Usage: tile datetime <@,?,rate>\n",
		"Getting datetime...\n\n",
		"Getting firmware version...\n\n",
		"Usage: tile gpsjam <@,?,rate>\n",
		"Getting GPS Jamming/Spoofing Indication...\n\n",
		"Spoofing unknown or deactivated",
		"No spoofing indicated",
		"Spoofing indicated",
		"Multiple spoofing indications",		
		"Usage: tile geospatial <@,?,rate>\n",
		"Getting geospatial information...\n\n",
		"Usage: tile gpio <?,mode>\n",
		"Getting gpio information...\n\n",
		"Analog, pin is internally disconnected and not used (default)",
		"Input, low-to-high transition exits sleep mode",
		"Input, high-to-low transition exits sleep mode",
		"Output, set low",
		"Output, set high",
		"Output, low indicates messages pending for client",
		"Output, high indicates messages pending for client",
		"Output, low while transmitting. Otherwise output is high",
		"Output, high while transmitting. Otherwise output is low",
		"Output, low indicates in sleep mode. Otherwise output is high",
		"Output, high indicates in sleep mode. Otherwise output is low",
		"Usage: tile gpsfix <@,?,rate>\n",
		"Getting GPS fix quality...\n\n",
		"No fix",
		"Dead reckoning only solution",
		"Standalone 2D solution",
		"Standalone 3D solution",
		"Differential 2D solution",
		"Differential 3D solution",
		"Combined GNSS + dead reckoning solution",
		"Time only solution",
		"Unknown",
		"Powering off tile...reset required\n\n",
		"Usage: tile powerstatus <@,?,rate>\n",
		"Getting power status...\n\n",
		"Getting restart information...\n\n",
		"Getting receive date message...\n\n",
		"Usage: tile rxtest <@,?,rate>\n",
		"Getting receive test information...\n\n",
		"Getting tile status...\n\n",
		"Usage: tile sleep <seconds or [YYYY-MM-DD hh:mm:ss]>\n",
		"Getting sleep information...\n\n",
		"Usage: tile send \"message\"\n",
		"Getting transmit data information...\n\n",
		"Usage: tile txmessages <count|delete|list>\n",
		"Getting messages to transmit information...\n\n",
		"Usage: tile rxmessages <count|delete[msgID]|read[msgID|o|n]>\n",
		"Getting messages received information...\n\n",
		"Usage: motion gyro|accel <enable|disable|rate [rate]|scale [f/s]>\n",		
		"Usage: motion detect <single|double|tilt|disable>\n",		
};
